services:
  - type: web
    name: phishguard
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_DIR
        value: /opt/render/project/data
      - key: PYTHON_VERSION
        value: 3.11
    disk:
      name: phishguard-data
      mountPath: /opt/render/project/data
      sizeGB: 1
